from __future__ import annotations

import sys
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

WEB_ROOT = PROJECT_ROOT / "apps" / "web"
PAGES_WORKFLOW = PROJECT_ROOT / ".github" / "workflows" / "pages.yml"


class WebStaticTests(unittest.TestCase):
    def test_frontend_files_are_present(self) -> None:
        self.assertTrue((PROJECT_ROOT / "Start-MicroScore.cmd").exists())
        self.assertTrue((WEB_ROOT / "index.html").exists())
        self.assertTrue((WEB_ROOT / "styles.css").exists())
        self.assertTrue((WEB_ROOT / "app.js").exists())
        self.assertTrue((WEB_ROOT / "mock-api.js").exists())
        self.assertTrue((WEB_ROOT / "application-intake.js").exists())
        self.assertTrue((WEB_ROOT / "portfolio-dashboard.js").exists())
        self.assertTrue((WEB_ROOT / "risk-detail.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "application-intake-smoke.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "portfolio-dashboard-smoke.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "frontend-workflow-smoke.js").exists())
        self.assertTrue((WEB_ROOT / ".nojekyll").exists())
        self.assertTrue((WEB_ROOT / "README.md").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon-32.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "apple-touch-icon.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "microscore-mark.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score-lockup.png").exists())

    def test_html_loads_styles_and_script(self) -> None:
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        css = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn('href="./styles.css"', html)
        self.assertIn('href="./assets/favicon.svg"', html)
        self.assertIn('href="./assets/favicon-32.png"', html)
        self.assertIn('href="./assets/apple-touch-icon.png"', html)
        self.assertIn('href="./assets/micro-score.png"', html)
        self.assertIn('src="./assets/micro-score-lockup.png?v=20260612-full"', html)
        self.assertIn('src="./assets/microscore-mark.svg"', html)
        self.assertIn('src="./application-intake.js?v=20260623-dashboard"', html)
        self.assertIn('src="./risk-detail.js?v=20260623-dashboard"', html)
        self.assertIn('src="./mock-api.js?v=20260716-invite-retry-v1"', html)
        self.assertIn('src="./portfolio-dashboard.js?v=20260623-dashboard"', html)
        self.assertIn('src="./app.js?v=20260716-invite-retry-v1"', html)
        self.assertIn("window.history.replaceState", html)
        self.assertIn("synthetic demo data only", html)
        self.assertIn('name="requested_amount" type="number" min="1000" max="100000000" step="1"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1" step="1000"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1000" step="1000"', html)
        self.assertIn('name="annual_income" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="total_outstanding_debt" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="avg_deposit_amount" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="debit_card_spending" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('id="applicationValidationSummary"', html)
        self.assertIn('class="application-form" novalidate', html)
        self.assertIn('id="authScreen"', html)
        self.assertIn('id="appShell"', html)
        self.assertIn('id="connection-title"', html)
        self.assertIn('class="api-settings"', html)
        self.assertIn('aria-label="Check API"', html)
        self.assertIn('id="demoModePill"', html)
        self.assertIn('id="resetDemoData"', html)
        self.assertIn('class="reviewer-snapshot"', html)
        self.assertIn("Research + product prototype", html)
        self.assertIn("Synthetic Pavlodar demo", html)
        self.assertIn("Human review support", html)
        self.assertIn("password123", html)
        self.assertIn('id="mfaCode"', html)
        self.assertNotIn('id="role"', html)
        self.assertIn(
            "grid-template-columns: minmax(190px, 1.15fr) minmax(180px, 0.85fr) auto auto",
            css,
        )
        self.assertIn('id="borrowerConsent"', html)
        self.assertIn("synthetic-data demo", html)
        self.assertIn("real borrower", html)
        self.assertIn('hidden', html)
        self.assertIn('id="borrowerView"', html)
        self.assertIn('id="borrowerApplicationHistory"', html)
        self.assertIn("My applications", html)
        self.assertNotIn('id="borrowerApplicationId"', html)
        self.assertIn('id="mfiView"', html)
        self.assertIn('id="adminView"', html)
        self.assertIn('id="staffForm"', html)
        self.assertIn('id="securityReadiness"', html)
        self.assertIn('id="mfaReadiness"', html)
        self.assertIn('id="staffUsers"', html)
        self.assertIn('id="refreshUsers"', html)
        self.assertIn('id="organizationForm"', html)
        self.assertIn('id="organizationDirectory"', html)
        self.assertIn('id="refreshOrganizations"', html)
        self.assertIn('id="applicationOrganization"', html)
        self.assertIn('id="staffOrganization"', html)
        self.assertIn('id="modelStatusPill"', html)
        self.assertIn('id="modelVersionForm"', html)
        self.assertIn('id="modelVersionRegistry"', html)
        self.assertIn('id="refreshModelVersions"', html)
        self.assertIn("Version registry", html)
        self.assertIn('id="simulationForm"', html)
        self.assertIn('id="runSimulation"', html)
        self.assertIn('id="simulationResults"', html)
        self.assertIn('id="simulationHistory"', html)
        self.assertIn('id="refreshSimulationHistory"', html)
        self.assertIn("Monte Carlo Lab", html)
        self.assertIn("This does not change borrower scores", html)
        self.assertIn('name="organization_id"', html)
        self.assertIn("Pavlodar Demo MFI", html)

    def test_hidden_screens_are_not_scrollable_before_login(self) -> None:
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn("[hidden]", styles)
        self.assertIn("display: none !important;", styles)
        self.assertIn(".reviewer-snapshot", styles)
        self.assertIn(".consent-panel", styles)
        self.assertIn("accent-color: var(--teal);", styles)

    def test_frontend_targets_current_api_contract(self) -> None:
        markup = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        script = (WEB_ROOT / "app.js").read_text(encoding="utf-8")
        mock_script = (WEB_ROOT / "mock-api.js").read_text(encoding="utf-8")
        intake_script = (WEB_ROOT / "application-intake.js").read_text(encoding="utf-8")
        portfolio_dashboard_script = (WEB_ROOT / "portfolio-dashboard.js").read_text(encoding="utf-8")
        risk_detail_script = (WEB_ROOT / "risk-detail.js").read_text(encoding="utf-8")

        expected_paths = [
            "/health",
            "/auth/register",
            "/auth/login",
            "/applications",
            "/timeline",
            "/mfi/applications",
            "/mfi/model-status",
            "/mfi/applications/export.csv",
            "/decision",
            "/review-packet",
            "/mfi/analytics/segments",
            "/mfi/analytics/policies",
            "/mfi/simulations/portfolio",
            "/mfi/simulations",
            "/mfi/analytics/decisions",
            "/admin/audit-events",
            "/admin/users",
            "/admin/security/readiness",
            "/admin/security/mfa-readiness",
            "/mfa/attest",
            "/disable",
            "/reactivate",
            "/admin/staff-invites",
            "/admin/staff-invites/health",
            "/delivery",
            "/rotate",
            "/admin/model-versions",
            "/admin/applications",
        ]
        for path in expected_paths:
            self.assertIn(path, script)
        self.assertIn("Scenario comparison", script)
        self.assertIn("Recommendation", script)
        self.assertIn("Local explanation", script)
        self.assertIn("MFI decision", script)
        self.assertIn("saveApplicationDecision", script)
        self.assertIn("Risk &amp; decision workspace", markup)
        self.assertIn("loadReviewPacket", script)
        self.assertIn("renderReviewPacket", script)
        self.assertIn("summarizeReviewPacket", script)
        self.assertIn("Affordability snapshot", script)
        self.assertIn("Decision history", script)
        self.assertIn("risk-readiness", script)
        self.assertIn("summarizeReviewPacket", risk_detail_script)
        self.assertIn("readiness_label", risk_detail_script)
        self.assertIn("Application timeline", script)
        self.assertIn("renderApplicationTimeline", script)
        self.assertIn("refreshBorrowerApplications", script)
        self.assertIn("renderBorrowerApplicationHistory", script)
        self.assertIn("openBorrowerApplication", script)
        self.assertIn("renderLifecycleProgress", script)
        self.assertIn("syncLifecycleControls", script)
        self.assertIn("Export CSV", markup)
        self.assertIn("exportApplicationsCsv", script)
        self.assertIn("microscore-applications.csv", script)
        self.assertIn("Analyst decisions", script)
        self.assertIn("renderPortfolioDecisionSnapshot", script)
        self.assertIn("Decision audit", markup)
        self.assertIn("decisionAuditRows", script)
        self.assertIn("proxy_sensitivity_delta", script)
        self.assertIn("HIGH_PROXY_SENSITIVITY_DELTA", script)
        self.assertIn("renderModelUseNotice", script)
        self.assertIn("Decision-support only", script)
        self.assertIn("Manual review required", script)
        self.assertIn("not validated for real lending decisions", script)
        self.assertIn("decision_support", script)
        self.assertIn("top_positive_factors", script)
        self.assertIn("top_protective_factors", script)
        self.assertIn("Portfolio", markup)
        self.assertIn("Settlement mix", script)
        self.assertIn("renderDistrictRiskRows", script)
        self.assertIn("renderSettlementTypeRows", script)
        self.assertIn("MicroScorePortfolioDashboard", script)
        self.assertIn("contextualSettlementShare", script)
        self.assertIn("Screenshot snapshot", script)
        self.assertIn("summarizePortfolioDashboard", portfolio_dashboard_script)
        self.assertIn("SETTLEMENT_ORDER", portfolio_dashboard_script)
        self.assertIn("CONTEXTUAL_SETTLEMENTS", portfolio_dashboard_script)
        self.assertIn("renderPortfolioOverview", script)
        self.assertIn("Policy Lab", markup)
        self.assertIn("renderPolicyAnalytics", script)
        self.assertIn("resetApplicationViews", script)
        self.assertIn("renderStateBlock", script)
        self.assertIn("setPanelState", script)
        self.assertIn("withButtonBusy", script)
        self.assertIn("Loading application queue", script)
        self.assertIn("Queue unavailable", script)
        self.assertIn("Scoring application", script)
        self.assertIn("Review packet unavailable", script)
        self.assertIn("Refreshing policy lab", script)
        self.assertIn("Decision audit unavailable", script)
        self.assertIn('removeItem("microscore.lastApplicationId")', script)
        self.assertIn("API_BASE_CANDIDATES", script)
        self.assertIn("MicroScoreMockApi", script)
        self.assertIn("MicroScoreMockApi", mock_script)
        self.assertIn("Static demo mode", script)
        self.assertIn("forceStaticDemo", script)
        self.assertIn("hostedStaticPage", script)
        self.assertIn("LOCAL_HOSTNAMES", script)
        self.assertIn("syncConnectionPanel", script)
        self.assertIn("Demo system", script)
        self.assertIn("Local system", script)
        self.assertIn("apiSettings.hidden = demoMode", script)
        self.assertIn("localhost plumbing", script)
        self.assertIn("resetStaticDemoData", script)
        self.assertIn("resetDemo", script)
        self.assertIn("borrowerConsent", script)
        self.assertIn("borrowerConsentAcknowledged", script)
        self.assertIn("validateApplicationPayload", script)
        self.assertIn("renderApplicationValidation", script)
        self.assertIn("clearApplicationFieldValidation", script)
        self.assertIn("Check the highlighted application fields", script)
        self.assertIn("DEMO_CONSENT_VERSION", script)
        self.assertIn("consent_confirmed", script)
        self.assertIn("consent_version", script)
        self.assertIn("logoutSession", script)
        self.assertIn('/auth/logout', script)
        self.assertIn('payload.role = "borrower"', script)
        self.assertIn("formatApiError", script)
        self.assertIn("formatSessionExpiry", script)
        self.assertIn("sessionExpiresAt", script)
        self.assertIn("session_ttl_seconds", script)
        self.assertIn("mfa_code", script)
        self.assertIn("session_expires_at", mock_script)
        self.assertIn("DEMO_SESSION_TTL_SECONDS", mock_script)
        self.assertIn("DEMO_MFA_CODE", mock_script)
        self.assertIn('"/me"', mock_script)
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".model-use-notice", styles)
        self.assertIn(".notice-caution", styles)
        self.assertIn(".state-block", styles)
        self.assertIn(".state-spinner", styles)
        self.assertIn(".checkbox-label", styles)
        self.assertIn("@keyframes stateSpin", styles)
        self.assertIn("button:disabled", styles)
        self.assertIn(".borrower-history-row", styles)
        self.assertIn(".lifecycle-progress", styles)
        self.assertIn("/mfi/applications/export.csv", mock_script)
        self.assertIn("/mfi/analytics/policies", mock_script)
        self.assertIn("/admin/applications", mock_script)
        self.assertIn("validateApplicationPrivacy", mock_script)
        self.assertIn("validateApplicationContract", mock_script)
        self.assertIn("findForbiddenSignalPaths", mock_script)
        self.assertIn("Remove sensitive personal fields", mock_script)
        self.assertIn("validateApplicationIntake", intake_script)
        self.assertIn("DISTRICT_SETTLEMENT_TYPES", intake_script)
        self.assertIn("Unexpected behavioral field", intake_script)
        self.assertIn('/auth/logout', mock_script)
        self.assertIn("Demo session expired", mock_script)
        self.assertIn("borrowerApplication", mock_script)
        self.assertIn("borrowerTimelineEvent", mock_script)
        self.assertIn("terminalApplicationStatuses", mock_script)
        self.assertIn("application_rescored", mock_script)
        self.assertIn("affordabilitySnapshot", mock_script)
        self.assertIn("lifecycleSummary", mock_script)
        self.assertIn("decision_history", mock_script)
        self.assertIn("passwordPolicyViolations", mock_script)
        self.assertIn("Public registration is limited to borrower accounts", mock_script)
        self.assertIn('"/admin/users"', mock_script)
        self.assertIn('"/admin/security/readiness"', mock_script)
        self.assertIn('"/admin/security/mfa-readiness"', mock_script)
        self.assertIn("securityReadiness", mock_script)
        self.assertIn("mfa_enforcement", mock_script)
        self.assertIn("Staff login requires an MFA-attested account", mock_script)
        self.assertIn("invite_delivery", mock_script)
        self.assertIn("invite_delivery_attempts", mock_script)
        self.assertIn("staff_user_created", mock_script)
        self.assertIn("staff_mfa_attested", mock_script)
        self.assertIn("staff_mfa_login_verified", mock_script)
        self.assertIn("staff_user_disabled", mock_script)
        self.assertIn("staff_user_reactivated", mock_script)
        self.assertIn("mfaReadiness", mock_script)
        self.assertIn("missing_mfa_count", mock_script)
        self.assertIn("Account disabled", mock_script)
        self.assertIn("MFA code required", mock_script)
        self.assertIn("Invalid MFA code", mock_script)
        self.assertIn('"/admin/staff-invites"', mock_script)
        self.assertIn('"/admin/staff-invites/health"', mock_script)
        self.assertIn("/delivery-attempts", mock_script)
        self.assertIn("retryStaffInviteDeliveryMatch", mock_script)
        self.assertIn('"/auth/accept-staff-invite"', mock_script)
        self.assertIn("staff_invite_created", mock_script)
        self.assertIn("staff_invite_delivery_attempted", mock_script)
        self.assertIn("staff_invite_delivered", mock_script)
        self.assertIn("staff_invite_rotated", mock_script)
        self.assertIn("staff_invite_accepted", mock_script)
        self.assertIn("staff_invite_revoked", mock_script)
        self.assertIn("staffInviteHealth", mock_script)
        self.assertIn("expiring_soon_count", mock_script)
        self.assertIn("staffInviteTokenId", mock_script)
        self.assertIn("publicStaffInvite", mock_script)
        self.assertIn("publicStaffInviteDeliveryAttempt", mock_script)
        self.assertIn("staffInviteDeliveryAttempts", mock_script)
        self.assertIn("recordStaffInviteDeliveryAttempt", mock_script)
        self.assertIn("staffInviteDeliveryProviderResult", mock_script)
        self.assertIn("manual_receipt", mock_script)
        self.assertIn("local_outbox", mock_script)
        self.assertIn("local_queue", mock_script)
        self.assertIn("local_fail", mock_script)
        self.assertIn("invite_url", mock_script)
        self.assertIn("delivery_url_base", mock_script)
        self.assertIn("delivery_attempt_count", mock_script)
        self.assertIn("last_delivery_provider", mock_script)
        self.assertIn("Staff invite has been revoked", mock_script)
        self.assertIn("Staff invite has expired", mock_script)
        self.assertIn("refreshStaffUsers", script)
        self.assertIn("refreshSecurityReadiness", script)
        self.assertIn("renderSecurityReadiness", script)
        self.assertIn("renderMfaReadiness", script)
        self.assertIn("attestStaffMfa", script)
        self.assertIn("createStaffUser", script)
        self.assertIn("disableStaffUser", script)
        self.assertIn("reactivateStaffUser", script)
        self.assertIn("data-attest-mfa-email", script)
        self.assertIn("data-disable-user-email", script)
        self.assertIn("data-reactivate-user-email", script)
        self.assertIn("refreshStaffInvites", script)
        self.assertIn("renderStaffInviteHealth", script)
        self.assertIn("createStaffInvite", script)
        self.assertIn("markStaffInviteDelivered", script)
        self.assertIn("retryStaffInviteDelivery", script)
        self.assertIn("rotateStaffInvite", script)
        self.assertIn("revokeStaffInvite", script)
        self.assertIn("data-retry-delivery-token", script)
        self.assertIn("data-deliver-invite-token", script)
        self.assertIn("data-rotate-invite-token", script)
        self.assertIn("data-revoke-invite-token", script)
        self.assertIn("queue_delivery", script)
        self.assertIn("Queue local delivery receipt", markup)
        self.assertIn("delivery_attempt", script)
        self.assertIn("Token preview", script)
        self.assertIn("one-time URL", script)
        self.assertIn("Staff Invite v3", markup)
        self.assertIn('id="staffInviteHealth"', markup)
        self.assertIn("organization_id", script)
        self.assertIn("mfiApplications", mock_script)
        self.assertIn("pavlodar-demo-mfi", mock_script)
        self.assertIn("refreshOrganizations", script)
        self.assertIn("createOrganization", script)
        self.assertIn("syncOrganizationSelect", script)
        self.assertIn("checkApiAndOrganizations", script)
        self.assertIn("refreshModelStatus", script)
        self.assertIn("refreshModelVersions", script)
        self.assertIn("createModelVersion", script)
        self.assertIn("activateModelVersion", script)
        self.assertIn("runPortfolioSimulation", script)
        self.assertIn("renderPortfolioSimulation", script)
        self.assertIn("renderSimulationScenario", script)
        self.assertIn("refreshSimulationHistory", script)
        self.assertIn("loadStoredSimulation", script)
        self.assertIn("portfolio_fingerprint", script)
        self.assertIn("portfolio_result_mean_standard_error", script)
        self.assertIn("probability_of_loss", script)
        self.assertIn("simulation-warnings", script)
        self.assertIn("stale_model_version", mock_script)
        self.assertIn("model_version_activated", mock_script)
        self.assertIn("activeModelVersion", mock_script)
        self.assertIn(".organization-form", styles)
        self.assertIn(".model-version-form", styles)
        self.assertIn(".model-version-card", styles)
        self.assertIn(".monte-carlo-panel", styles)
        self.assertIn(".simulation-form", styles)
        self.assertIn(".simulation-card", styles)
        self.assertIn(".simulation-warnings", styles)
        self.assertIn(".simulation-history-row", styles)
        self.assertIn(".risk-readiness", styles)
        self.assertIn(".affordability-panel", styles)
        self.assertIn(".decision-history", styles)
        self.assertIn(".validation-summary", styles)
        self.assertIn(".field-invalid", styles)
        self.assertIn(".field-error", styles)
        self.assertIn(".settlement-bars", styles)
        self.assertIn(".settlement-risk-row", styles)
        self.assertIn(".portfolio-snapshot-note", styles)
        self.assertIn(".settlement-fill-industrial_city", styles)
        self.assertIn("simulatePortfolio", mock_script)
        self.assertIn("portfolioFingerprint", mock_script)
        self.assertIn("simulationStandardError", mock_script)
        self.assertIn("simulationSummary", mock_script)
        self.assertIn("seededRandom", mock_script)
        self.assertIn("scenarioShifts", mock_script)
        self.assertIn("portfolio_simulation_run", mock_script)
        self.assertIn("enterDemoWorkspace", script)
        self.assertIn("API settings", markup)
        self.assertIn("roleAllowedViews", script)
        self.assertIn("configureRoleNavigation", script)
        self.assertIn("setAppMode", script)
        self.assertIn("routeToView", script)
        self.assertIn("viewToRoute", script)
        self.assertIn("roleDefaultRoutes", script)
        self.assertIn("applyRoute", script)
        self.assertIn("replaceRoute", script)
        self.assertIn("hashchange", script)
        self.assertIn("#/login", script)
        self.assertIn("#/borrower", script)
        self.assertIn("#/mfi", script)
        self.assertIn("#/admin", script)
        self.assertIn('data-roles="borrower"', markup)
        self.assertIn('data-roles="mfi_analyst admin"', markup)
        self.assertIn('data-roles="admin"', markup)

    def test_one_click_launcher_is_documented(self) -> None:
        root_readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        web_readme = (WEB_ROOT / "README.md").read_text(encoding="utf-8")
        command_file = (PROJECT_ROOT / "Start-MicroScore.cmd").read_text(encoding="utf-8")

        self.assertIn("Start-MicroScore.cmd", root_readme)
        self.assertIn("Start-MicroScore.cmd", web_readme)
        self.assertIn("microscore_api.dev", command_file)

    def test_static_demo_deployment_is_configured(self) -> None:
        workflow = PAGES_WORKFLOW.read_text(encoding="utf-8")
        deployment_doc = (PROJECT_ROOT / "docs" / "STATIC_DEMO_DEPLOYMENT.md").read_text(
            encoding="utf-8",
        )

        self.assertIn("actions/configure-pages@v6", workflow)
        self.assertIn("actions/upload-pages-artifact@v5", workflow)
        self.assertIn("actions/deploy-pages@v5", workflow)
        self.assertIn("pages: write", workflow)
        self.assertIn("id-token: write", workflow)
        self.assertIn("path: apps/web", workflow)
        self.assertIn("GitHub Pages", deployment_doc)
        self.assertIn("application-intake.js", deployment_doc)
        self.assertIn("portfolio-dashboard.js", deployment_doc)
        self.assertIn("mock-api.js", deployment_doc)
        self.assertIn("synthetic", deployment_doc)


if __name__ == "__main__":
    unittest.main()
