from __future__ import annotations

import sys
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

WEB_ROOT = PROJECT_ROOT / "apps" / "web"
PAGES_WORKFLOW = PROJECT_ROOT / ".github" / "workflows" / "pages.yml"


class WebStaticTests(unittest.TestCase):
    def test_frontend_files_are_present(self) -> None:
        self.assertTrue((PROJECT_ROOT / "Start-MicroScore.cmd").exists())
        self.assertTrue((WEB_ROOT / "index.html").exists())
        self.assertTrue((WEB_ROOT / "styles.css").exists())
        self.assertTrue((WEB_ROOT / "app.js").exists())
        self.assertTrue((WEB_ROOT / "mock-api.js").exists())
        self.assertTrue((WEB_ROOT / "application-intake.js").exists())
        self.assertTrue((WEB_ROOT / "portfolio-dashboard.js").exists())
        self.assertTrue((WEB_ROOT / "risk-detail.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "application-intake-smoke.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "portfolio-dashboard-smoke.js").exists())
        self.assertTrue((PROJECT_ROOT / "scripts" / "frontend-workflow-smoke.js").exists())
        self.assertTrue((WEB_ROOT / ".nojekyll").exists())
        self.assertTrue((WEB_ROOT / "README.md").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon-32.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "apple-touch-icon.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "microscore-mark.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score-lockup.png").exists())

    def test_html_loads_styles_and_script(self) -> None:
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        css = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn('href="./styles.css?v=20260814-monte-carlo-evidence-dossier-v1"', html)
        self.assertIn('href="./assets/favicon.svg"', html)
        self.assertIn('href="./assets/favicon-32.png"', html)
        self.assertIn('href="./assets/apple-touch-icon.png"', html)
        self.assertIn('href="./assets/micro-score.png"', html)
        self.assertIn('src="./assets/micro-score-lockup.png?v=20260612-full"', html)
        self.assertIn('src="./assets/microscore-mark.svg"', html)
        self.assertIn('src="./application-intake.js?v=20260623-dashboard"', html)
        self.assertIn('src="./risk-detail.js?v=20260717-pilot-readiness-v1"', html)
        self.assertIn('src="./mock-api.js?v=20260814-monte-carlo-evidence-dossier-v1"', html)
        self.assertIn('src="./portfolio-dashboard.js?v=20260623-dashboard"', html)
        self.assertIn('src="./app.js?v=20260814-monte-carlo-evidence-dossier-v1"', html)
        self.assertIn("window.history.replaceState", html)
        self.assertIn("synthetic demo data only", html)
        self.assertIn('class="workspace-hero"', html)
        self.assertIn("Pre-pilot operating picture", html)
        self.assertIn("PG adapter 52/52", html)
        self.assertIn("Human review only", html)
        self.assertIn("Synthetic demo", html)
        self.assertIn("--brand-gradient", css)
        self.assertIn("--surface-glass", css)
        self.assertIn("--focus-ring", css)
        self.assertIn(".workspace-hero", css)
        self.assertIn("backdrop-filter: blur", css)
        self.assertIn("text-rendering: optimizeLegibility", css)
        self.assertIn('id="mfiView" class="view-grid mfi-workspace"', html)
        self.assertIn('id="mfiDetailPanel" class="panel mfi-detail-panel mfi-section-panel"', html)
        mfi_view_start = html.index('id="mfiView" class="view-grid mfi-workspace"')
        queue_heading = html.index('id="mfi-title"', mfi_view_start)
        risk_heading = html.index("Risk &amp; decision workspace", mfi_view_start)
        queue_panel_start = html.index('id="mfiQueuePanel"', mfi_view_start)
        risk_panel_start = html.index('id="mfiDetailPanel"', mfi_view_start)
        self.assertLess(queue_heading, risk_heading)
        self.assertIn(
            'id="mfiQueuePanel" class="panel mfi-section-panel"',
            html[queue_panel_start : queue_panel_start + 120],
        )
        self.assertIn(
            'id="mfiDetailPanel" class="panel mfi-detail-panel mfi-section-panel"',
            html[risk_panel_start : risk_panel_start + 120],
        )
        self.assertIn(".mfi-workspace", css)
        self.assertIn(".mfi-workspace > .portfolio-panel", css)
        self.assertIn(".mfi-workspace > .mfi-detail-panel", css)
        self.assertIn('class="mfi-command-strip"', html)
        self.assertIn("Analyst command flow", html)
        self.assertIn("Queue", html)
        self.assertIn("Risk", html)
        self.assertIn("Policy", html)
        self.assertIn("Monte Carlo", html)
        self.assertIn(".mfi-command-strip", css)
        self.assertIn(".mfi-flow-steps", css)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr))", css)
        self.assertIn('data-mfi-jump="mfiQueuePanel"', html)
        self.assertIn('data-mfi-jump="mfiDetailPanel"', html)
        self.assertIn('data-mfi-jump="policyLabPanel"', html)
        self.assertIn('data-mfi-jump="monteCarloPanel"', html)
        self.assertIn('id="mfiQueuePanel"', html)
        self.assertIn('id="mfiDetailPanel"', html)
        self.assertIn('id="policyLabPanel"', html)
        self.assertIn('id="monteCarloPanel"', html)
        self.assertIn(".mfi-section-panel", css)
        self.assertIn("scroll-margin-top: 24px", css)
        self.assertIn('id="selectedApplicationBrief"', html)
        self.assertIn('id="mfiInspectorTabs"', html)
        self.assertIn('data-mfi-inspector-tab="summary"', html)
        self.assertIn('data-mfi-inspector-tab="evidence"', html)
        self.assertIn('data-mfi-inspector-tab="decision"', html)
        self.assertIn('data-mfi-inspector-tab="timeline"', html)
        self.assertIn('data-mfi-inspector-panel="summary"', html)
        self.assertIn('data-mfi-inspector-panel="evidence"', html)
        self.assertIn('id="mfiDecisionWorkspace"', html)
        self.assertIn('id="decisionHistoryPanel"', html)
        self.assertIn('id="mfiTimelinePanel"', html)
        self.assertIn('id="mfiQueueControls"', html)
        self.assertIn('id="mfiQueueSearch"', html)
        self.assertIn('id="mfiQueueStatus"', html)
        self.assertIn('id="mfiQueueRisk"', html)
        self.assertIn('id="mfiQueueDistrict"', html)
        self.assertIn('id="mfiQueueSort"', html)
        self.assertIn('id="clearMfiQueueFilters"', html)
        self.assertIn('id="mfiQueueSummary"', html)
        self.assertIn(".mfi-brief-card", css)
        self.assertIn(".mfi-brief-grid", css)
        self.assertIn(".mfi-brief-action", css)
        self.assertIn(".mfi-inspector-tabs", css)
        self.assertIn(".mfi-decision-workspace", css)
        self.assertIn(".decision-command-card", css)
        self.assertIn("[data-mfi-inspector-panel][hidden]", css)
        self.assertIn(".mfi-queue-controls", css)
        self.assertIn(".mfi-queue-summary", css)
        self.assertIn(".mfi-queue-summary.filters-active", css)
        self.assertIn(".mfi-queue-list", css)
        self.assertIn(".mfi-queue-card", css)
        self.assertIn(".mfi-queue-card-meta", css)
        self.assertIn(".mfi-queue-risk", css)
        self.assertIn(".mfi-queue-card.selected", css)
        self.assertIn("position: sticky", css)
        self.assertIn("max-height: calc(100vh - 40px)", css)
        self.assertIn("overscroll-behavior: contain", css)
        self.assertIn("grid-template-columns: repeat(auto-fit, minmax(160px, 1fr))", css)
        self.assertIn(".simulation-form > label", css)
        self.assertIn(".simulation-actions", css)
        self.assertIn("#runSimulation", css)
        self.assertIn("#runPolicySweep", css)
        self.assertIn("#runSensitivitySweep", css)
        self.assertIn("grid-column: 1 / -1", css)
        self.assertIn("white-space: normal", css)
        self.assertIn('name="requested_amount" type="number" min="1000" max="100000000" step="1"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1" step="1000"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1000" step="1000"', html)
        self.assertIn('name="annual_income" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="total_outstanding_debt" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="avg_deposit_amount" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('name="debit_card_spending" type="number" min="0" max="10000000000" step="1"', html)
        self.assertIn('id="applicationValidationSummary"', html)
        self.assertIn('class="application-form" novalidate', html)
        self.assertIn('id="authScreen"', html)
        self.assertIn('id="appShell"', html)
        self.assertIn('id="connection-title"', html)
        self.assertIn('class="api-settings"', html)
        self.assertIn('aria-label="Check API"', html)
        self.assertIn('id="demoModePill"', html)
        self.assertIn('id="resetDemoData"', html)
        self.assertIn('class="reviewer-snapshot"', html)
        self.assertIn("Research + product prototype", html)
        self.assertIn("Synthetic Pavlodar demo", html)
        self.assertIn("Human review support", html)
        self.assertIn("password123", html)
        self.assertIn('id="mfaCode"', html)
        self.assertNotIn('id="role"', html)
        self.assertIn(
            "grid-template-columns: minmax(190px, 1.15fr) minmax(180px, 0.85fr) auto auto",
            css,
        )
        self.assertIn('id="borrowerConsent"', html)
        self.assertIn("synthetic-data demo", html)
        self.assertIn("real borrower", html)
        self.assertIn('hidden', html)
        self.assertIn('id="borrowerView"', html)
        self.assertIn('id="borrowerApplicationHistory"', html)
        self.assertIn("My applications", html)
        self.assertNotIn('id="borrowerApplicationId"', html)
        self.assertIn('id="mfiView"', html)
        self.assertIn('id="adminView"', html)
        self.assertIn('id="prePilotReadiness"', html)
        self.assertIn("Pre-Pilot Gate v1", html)
        self.assertIn('id="postgresqlReadiness"', html)
        self.assertIn("PostgreSQL Readiness v1", html)
        self.assertIn('id="identityReadiness"', html)
        self.assertIn("Security Evidence Room v1", html)
        self.assertIn("Identity and access evidence", html)
        self.assertIn('id="staffForm"', html)
        self.assertIn('id="securityReadiness"', html)
        self.assertIn('id="mfaReadiness"', html)
        self.assertIn('id="staffUsers"', html)
        self.assertIn('id="staffInviteDeliveryReadiness"', html)
        self.assertIn('id="staffInviteDeliveryAdapterReadiness"', html)
        self.assertIn('id="staffInviteDeliveryOutbox"', html)
        self.assertIn('id="refreshUsers"', html)
        self.assertIn('id="organizationForm"', html)
        self.assertIn('id="organizationDirectory"', html)
        self.assertIn('id="refreshOrganizations"', html)
        self.assertIn('id="applicationOrganization"', html)
        self.assertIn('id="staffOrganization"', html)
        self.assertIn('id="modelStatusPill"', html)
        self.assertIn('id="modelVersionForm"', html)
        self.assertIn('id="modelVersionRegistry"', html)
        self.assertIn('id="refreshModelVersions"', html)
        self.assertIn("Version registry", html)
        self.assertIn('id="simulationForm"', html)
        self.assertIn('id="runSimulation"', html)
        self.assertIn('id="runPolicySweep"', html)
        self.assertIn('id="runSensitivitySweep"', html)
        self.assertIn('id="simulationResults"', html)
        self.assertIn('id="policySweepResults"', html)
        self.assertIn('id="sensitivityResults"', html)
        self.assertIn('id="committeeBrief"', html)
        self.assertIn('id="riskAppetiteGate"', html)
        self.assertIn('id="pilotMonitoringPlan"', html)
        self.assertIn('id="pilotEvidenceDossier"', html)
        self.assertIn('id="simulationHistory"', html)
        self.assertIn('id="refreshSimulationHistory"', html)
        self.assertIn("Monte Carlo Lab", html)
        self.assertIn("Run policy sweep", html)
        self.assertIn("Run sensitivity", html)
        self.assertIn("committee-ready brief", html)
        self.assertIn("pilot risk appetite", html)
        self.assertIn("pilot monitoring plan", html)
        self.assertIn("pilot evidence dossier", html)
        self.assertIn("This does not change borrower scores", html)
        self.assertIn('name="organization_id"', html)
        self.assertIn("Pavlodar Demo MFI", html)

    def test_hidden_screens_are_not_scrollable_before_login(self) -> None:
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn("[hidden]", styles)
        self.assertIn("display: none !important;", styles)
        self.assertIn(".reviewer-snapshot", styles)
        self.assertIn(".consent-panel", styles)
        self.assertIn("accent-color: var(--teal);", styles)

    def test_frontend_targets_current_api_contract(self) -> None:
        markup = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        script = (WEB_ROOT / "app.js").read_text(encoding="utf-8")
        mock_script = (WEB_ROOT / "mock-api.js").read_text(encoding="utf-8")
        intake_script = (WEB_ROOT / "application-intake.js").read_text(encoding="utf-8")
        portfolio_dashboard_script = (WEB_ROOT / "portfolio-dashboard.js").read_text(encoding="utf-8")
        risk_detail_script = (WEB_ROOT / "risk-detail.js").read_text(encoding="utf-8")

        expected_paths = [
            "/health",
            "/auth/register",
            "/auth/login",
            "/applications",
            "/timeline",
            "/mfi/applications",
            "/mfi/model-status",
            "/mfi/applications/export.csv",
            "/decision",
            "/review-packet",
            "/mfi/analytics/segments",
            "/mfi/analytics/policies",
            "/mfi/simulations/portfolio",
            "/mfi/simulations",
            "/mfi/analytics/decisions",
            "/admin/audit-events",
            "/admin/users",
            "/admin/governance/pre-pilot-readiness",
            "/admin/storage/postgresql-readiness",
            "/admin/security/readiness",
            "/admin/security/identity-readiness",
            "/admin/security/mfa-readiness",
            "/mfa/attest",
            "/disable",
            "/reactivate",
            "/admin/staff-invites",
            "/admin/staff-invites/health",
            "/admin/staff-invites/delivery-readiness",
            "/admin/staff-invites/delivery-adapter-readiness",
            "/admin/staff-invites/delivery-outbox",
            "/delivery",
            "/rotate",
            "/admin/model-versions",
            "/admin/applications",
        ]
        for path in expected_paths:
            self.assertIn(path, script)
        self.assertIn("Scenario comparison", script)
        self.assertIn("Recommendation", script)
        self.assertIn("Local explanation", script)
        self.assertIn("MFI decision", script)
        self.assertIn("saveApplicationDecision", script)
        self.assertIn("Risk &amp; decision workspace", markup)
        self.assertIn("loadReviewPacket", script)
        self.assertIn("renderReviewPacket", script)
        self.assertIn("renderReviewActionPlan", script)
        self.assertIn("reviewActionPlan", script)
        self.assertIn("selectedReviewPacket", script)
        self.assertIn("summarizeReviewPacket", script)
        self.assertIn("Affordability snapshot", script)
        self.assertIn("Action plan", script)
        self.assertIn("Checklist blockers", script)
        self.assertIn("Allowed decisions", script)
        self.assertIn("Decision history", script)
        self.assertIn("risk-readiness", script)
        self.assertIn("buildReviewActionPlan", risk_detail_script)
        self.assertIn("terminal_locked", risk_detail_script)
        self.assertIn("rescore_required", risk_detail_script)
        self.assertIn("summarizeReviewPacket", risk_detail_script)
        self.assertIn("readiness_label", risk_detail_script)
        self.assertIn("Application timeline", script)
        self.assertIn("renderApplicationTimeline", script)
        self.assertIn("refreshBorrowerApplications", script)
        self.assertIn("renderBorrowerApplicationHistory", script)
        self.assertIn("renderBorrowerApplication", script)
        self.assertIn("renderBorrowerTimeline", script)
        self.assertIn("borrowerStatusMeta", script)
        self.assertIn("openBorrowerApplication", script)
        self.assertIn("renderLifecycleProgress", script)
        self.assertIn("borrower-privacy-note", script)
        self.assertIn("does not show internal scores", script)
        self.assertIn("status timeline", markup)
        self.assertIn("syncLifecycleControls", script)
        self.assertIn("Export CSV", markup)
        self.assertIn("exportApplicationsCsv", script)
        self.assertIn("microscore-applications.csv", script)
        self.assertIn("Analyst decisions", script)
        self.assertIn("renderPortfolioDecisionSnapshot", script)
        self.assertIn("Decision audit", markup)
        self.assertIn("decisionAuditRows", script)
        self.assertIn("proxy_sensitivity_delta", script)
        self.assertIn("HIGH_PROXY_SENSITIVITY_DELTA", script)
        self.assertIn("renderModelUseNotice", script)
        self.assertIn("Decision-support only", script)
        self.assertIn("Manual review required", script)
        self.assertIn("not validated for real lending decisions", script)
        self.assertIn("decision_support", script)
        self.assertIn("top_positive_factors", script)
        self.assertIn("top_protective_factors", script)
        self.assertIn("Portfolio", markup)
        self.assertIn("Settlement mix", script)
        self.assertIn("renderDistrictRiskRows", script)
        self.assertIn("renderSettlementTypeRows", script)
        self.assertIn("MicroScorePortfolioDashboard", script)
        self.assertIn("contextualSettlementShare", script)
        self.assertIn("Screenshot snapshot", script)
        self.assertIn("summarizePortfolioDashboard", portfolio_dashboard_script)
        self.assertIn("SETTLEMENT_ORDER", portfolio_dashboard_script)
        self.assertIn("CONTEXTUAL_SETTLEMENTS", portfolio_dashboard_script)
        self.assertIn("renderPortfolioOverview", script)
        self.assertIn("Policy Lab", markup)
        self.assertIn("renderPolicyAnalytics", script)
        self.assertIn("resetApplicationViews", script)
        self.assertIn("renderStateBlock", script)
        self.assertIn("setPanelState", script)
        self.assertIn("renderPrePilotReadiness", script)
        self.assertIn("renderPostgresqlReadiness", script)
        self.assertIn("pre_pilot_readiness", script)
        self.assertIn("postgresql_readiness", script)
        self.assertIn("Migration artifacts", script)
        self.assertIn("migration_artifact_count", script)
        self.assertIn("latest_migration_version", script)
        self.assertIn("disposable_migration_ci_present", script)
        self.assertIn("PG CI", script)
        self.assertIn("repository_adapter_contract_status", script)
        self.assertIn("repository_adapter_contract_method_count", script)
        self.assertIn("repository_adapter_implemented_method_count", script)
        self.assertIn("repository_adapter_stage", script)
        self.assertIn("Adapter", script)
        self.assertIn("Pre-Pilot Gate", script)
        self.assertIn("PostgreSQL readiness", script)
        self.assertIn("withButtonBusy", script)
        self.assertIn("Loading application queue", script)
        self.assertIn("Queue unavailable", script)
        self.assertIn("Scoring application", script)
        self.assertIn("Review packet unavailable", script)
        self.assertIn("Refreshing policy lab", script)
        self.assertIn("Decision audit unavailable", script)
        self.assertIn('removeItem("microscore.lastApplicationId")', script)
        self.assertIn("API_BASE_CANDIDATES", script)
        self.assertIn("MicroScoreMockApi", script)
        self.assertIn("MicroScoreMockApi", mock_script)
        self.assertIn("Static demo mode", script)
        self.assertIn("forceStaticDemo", script)
        self.assertIn("hostedStaticPage", script)
        self.assertIn("LOCAL_HOSTNAMES", script)
        self.assertIn("syncConnectionPanel", script)
        self.assertIn("Demo system", script)
        self.assertIn("Local system", script)
        self.assertIn("apiSettings.hidden = demoMode", script)
        self.assertIn("localhost plumbing", script)
        self.assertIn("resetStaticDemoData", script)
        self.assertIn("resetDemo", script)
        self.assertIn("borrowerConsent", script)
        self.assertIn("borrowerConsentAcknowledged", script)
        self.assertIn("validateApplicationPayload", script)
        self.assertIn("renderApplicationValidation", script)
        self.assertIn("clearApplicationFieldValidation", script)
        self.assertIn("Check the highlighted application fields", script)
        self.assertIn("DEMO_CONSENT_VERSION", script)
        self.assertIn("consent_confirmed", script)
        self.assertIn("consent_version", script)
        self.assertIn("logoutSession", script)
        self.assertIn('/auth/logout', script)
        self.assertIn('payload.role = "borrower"', script)
        self.assertIn("formatApiError", script)
        self.assertIn("formatSessionExpiry", script)
        self.assertIn("sessionExpiresAt", script)
        self.assertIn("session_ttl_seconds", script)
        self.assertIn("mfa_code", script)
        self.assertIn("session_expires_at", mock_script)
        self.assertIn("DEMO_SESSION_TTL_SECONDS", mock_script)
        self.assertIn("DEMO_MFA_CODE", mock_script)
        self.assertIn('"/me"', mock_script)
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".model-use-notice", styles)
        self.assertIn(".notice-caution", styles)
        self.assertIn(".state-block", styles)
        self.assertIn(".pre-pilot-readiness", styles)
        self.assertIn(".pre-pilot-hero", styles)
        self.assertIn(".postgresql-readiness", styles)
        self.assertIn(".postgresql-hero", styles)
        self.assertIn(".state-spinner", styles)
        self.assertIn(".checkbox-label", styles)
        self.assertIn("@keyframes stateSpin", styles)
        self.assertIn("button:disabled", styles)
        self.assertIn(".borrower-history-row", styles)
        self.assertIn(".borrower-portal-card", styles)
        self.assertIn(".borrower-status-banner", styles)
        self.assertIn(".borrower-summary-grid", styles)
        self.assertIn(".borrower-privacy-note", styles)
        self.assertIn(".borrower-timeline", styles)
        self.assertIn(".lifecycle-progress", styles)
        self.assertIn("/mfi/applications/export.csv", mock_script)
        self.assertIn("/mfi/analytics/policies", mock_script)
        self.assertIn("/admin/applications", mock_script)
        self.assertIn("validateApplicationPrivacy", mock_script)
        self.assertIn("validateApplicationContract", mock_script)
        self.assertIn("findForbiddenSignalPaths", mock_script)
        self.assertIn("Remove sensitive personal fields", mock_script)
        self.assertIn("validateApplicationIntake", intake_script)
        self.assertIn("DISTRICT_SETTLEMENT_TYPES", intake_script)
        self.assertIn("Unexpected behavioral field", intake_script)
        self.assertIn('/auth/logout', mock_script)
        self.assertIn("Demo session expired", mock_script)
        self.assertIn("borrowerApplication", mock_script)
        self.assertIn("borrowerTimelineEvent", mock_script)
        self.assertIn("terminalApplicationStatuses", mock_script)
        self.assertIn("application_rescored", mock_script)
        self.assertIn("affordabilitySnapshot", mock_script)
        self.assertIn("lifecycleSummary", mock_script)
        self.assertIn("decision_history", mock_script)
        self.assertIn("passwordPolicyViolations", mock_script)
        self.assertIn("Public registration is limited to borrower accounts", mock_script)
        self.assertIn('"/admin/users"', mock_script)
        self.assertIn('"/admin/governance/pre-pilot-readiness"', mock_script)
        self.assertIn('"/admin/storage/postgresql-readiness"', mock_script)
        self.assertIn("prePilotReadiness", mock_script)
        self.assertIn("postgresqlMigrationReadiness", mock_script)
        self.assertIn("PRE_PILOT_READINESS_LIMITATION", mock_script)
        self.assertIn("POSTGRESQL_READINESS_LIMITATION", mock_script)
        self.assertIn("POSTGRESQL_MIGRATION_ARTIFACTS", mock_script)
        self.assertIn("0001_initial_schema", mock_script)
        self.assertIn("migrations/postgresql/0001_initial_schema.sql", mock_script)
        self.assertIn("postgresql_schema_inventory", mock_script)
        self.assertIn("postgresql_versioned_migration_artifacts", mock_script)
        self.assertIn("postgresql_disposable_migration_ci", mock_script)
        self.assertIn("disposable_migration_ci_present", mock_script)
        self.assertIn("POSTGRESQL_REPOSITORY_ADAPTER_CONTRACT", mock_script)
        self.assertIn("postgresql-repository-adapter-v9", mock_script)
        self.assertIn("implemented", mock_script)
        self.assertIn("all_repository_method_groups_v1", mock_script)
        self.assertIn("postgresql_repository_adapter_contract", mock_script)
        self.assertIn("repository_adapter_contract_method_count", mock_script)
        self.assertIn("postgresql_model_registry_read_adapter", mock_script)
        self.assertIn("postgresql_model_registry_method_group_adapter", mock_script)
        self.assertIn("postgresql_audit_method_group_adapter", mock_script)
        self.assertIn("postgresql_organization_method_group_adapter", mock_script)
        self.assertIn("postgresql_identity_access_method_group_adapter", mock_script)
        self.assertIn("postgresql_staff_invites_delivery_method_group_adapter", mock_script)
        self.assertIn("postgresql_application_lifecycle_method_group_adapter", mock_script)
        self.assertIn("postgresql_portfolio_analytics_method_group_adapter", mock_script)
        self.assertIn("repository_adapter_implemented_method_count", mock_script)
        self.assertIn("repository_adapter_completed_method_group_count", mock_script)
        self.assertIn("repository_adapter_audit_group_present", mock_script)
        self.assertIn("repository_adapter_organization_group_present", mock_script)
        self.assertIn("repository_adapter_identity_access_group_present", mock_script)
        self.assertIn("repository_adapter_staff_invites_delivery_group_present", mock_script)
        self.assertIn("repository_adapter_application_lifecycle_group_present", mock_script)
        self.assertIn("repository_adapter_portfolio_analytics_group_present", mock_script)
        self.assertIn("migration_artifact_count", mock_script)
        self.assertIn("postgresql_disposable_ci", mock_script)
        self.assertIn("production_data_allowed", mock_script)
        self.assertIn("public_demo_allowed", mock_script)
        self.assertIn("monte_carlo_evidence", mock_script)
        self.assertIn('"/admin/security/readiness"', mock_script)
        self.assertIn('"/admin/security/identity-readiness"', mock_script)
        self.assertIn('"/admin/security/mfa-readiness"', mock_script)
        self.assertIn("securityReadiness", mock_script)
        self.assertIn("identityReadiness", mock_script)
        self.assertIn("auth_provider_mode", mock_script)
        self.assertIn("components", mock_script)
        self.assertIn("production_blockers", mock_script)
        self.assertIn("sqlite_static_demo", mock_script)
        self.assertIn("not a completed production security review", mock_script)
        self.assertIn("mfa_enforcement", mock_script)
        self.assertIn("mfa_challenge_failures", mock_script)
        self.assertIn("Staff login requires an MFA-attested account", mock_script)
        self.assertIn("invite_delivery", mock_script)
        self.assertIn("invite_delivery_attempts", mock_script)
        self.assertIn("staff_user_created", mock_script)
        self.assertIn("staff_mfa_attested", mock_script)
        self.assertIn("staff_mfa_login_verified", mock_script)
        self.assertIn("staff_mfa_challenge_failed", mock_script)
        self.assertIn("staff_user_disabled", mock_script)
        self.assertIn("staff_user_reactivated", mock_script)
        self.assertIn("staff_session_revoked", mock_script)
        self.assertIn("mfaReadiness", mock_script)
        self.assertIn("recordStaffMfaChallengeFailed", mock_script)
        self.assertIn("recentStaffMfaFailures", mock_script)
        self.assertIn("missing_mfa_count", mock_script)
        self.assertIn("Account disabled", mock_script)
        self.assertIn("MFA code required", mock_script)
        self.assertIn("Invalid MFA code", mock_script)
        self.assertIn('"/admin/staff-invites"', mock_script)
        self.assertIn('"/admin/staff-sessions"', mock_script)
        self.assertIn('"/admin/staff-invites/health"', mock_script)
        self.assertIn('"/admin/staff-invites/delivery-readiness"', mock_script)
        self.assertIn('"/admin/staff-invites/delivery-adapter-readiness"', mock_script)
        self.assertIn('"/admin/staff-invites/delivery-outbox"', mock_script)
        self.assertIn('"/admin/staff-invites/delivery-outbox/run"', mock_script)
        self.assertIn('"/webhooks/staff-invite-delivery"', mock_script)
        self.assertIn("/delivery-events", mock_script)
        self.assertIn("/delivery-attempts", mock_script)
        self.assertIn("retryStaffInviteDeliveryMatch", mock_script)
        self.assertIn('"/auth/accept-staff-invite"', mock_script)
        self.assertIn("staff_invite_created", mock_script)
        self.assertIn("staff_invite_delivery_attempted", mock_script)
        self.assertIn("staff_invite_delivery_webhook_received", mock_script)
        self.assertIn("staff_invite_delivery_worker_run", mock_script)
        self.assertIn("staff_invite_delivered", mock_script)
        self.assertIn("staff_invite_rotated", mock_script)
        self.assertIn("staff_invite_accepted", mock_script)
        self.assertIn("staff_invite_revoked", mock_script)
        self.assertIn("staffInviteHealth", mock_script)
        self.assertIn("inviteDeliveryReadiness", mock_script)
        self.assertIn("inviteDeliveryAdapterReadiness", mock_script)
        self.assertIn("INVITE_DELIVERY_ADAPTER_LIMITATION", mock_script)
        self.assertIn("external_send_adapter_disabled", mock_script)
        self.assertIn("invite_secret_material_not_available", mock_script)
        self.assertIn("adapter_idempotency_key", mock_script)
        self.assertIn("raw_invite_token", mock_script)
        self.assertIn("inviteDeliveryOutbox", mock_script)
        self.assertIn("runInviteDeliveryOutbox", mock_script)
        self.assertIn("staffInviteDeliveryOutboxItem", mock_script)
        self.assertIn("dead_letter", mock_script)
        self.assertIn("retry_scheduled", mock_script)
        self.assertIn("delivery_provider_not_production_ready", mock_script)
        self.assertIn("delivery_provider_configuration_missing", mock_script)
        self.assertIn("MICROSCORE_TRANSACTIONAL_EMAIL_API_KEY", mock_script)
        self.assertIn("transactional_email_contract", mock_script)
        self.assertIn("without sending external email", mock_script)
        self.assertIn("expiring_soon_count", mock_script)
        self.assertIn("staffInviteTokenId", mock_script)
        self.assertIn("publicStaffInvite", mock_script)
        self.assertIn("publicStaffInviteDeliveryAttempt", mock_script)
        self.assertIn("publicStaffInviteDeliveryWebhookEvent", mock_script)
        self.assertIn("staffInviteDeliveryAttempts", mock_script)
        self.assertIn("staffInviteDeliveryEvents", mock_script)
        self.assertIn("recordStaffInviteDeliveryAttempt", mock_script)
        self.assertIn("recordStaffInviteDeliveryWebhookEvent", mock_script)
        self.assertIn("staffInviteDeliveryProviderResult", mock_script)
        self.assertIn("manual_receipt", mock_script)
        self.assertIn("local_outbox", mock_script)
        self.assertIn("local_queue", mock_script)
        self.assertIn("local_fail", mock_script)
        self.assertIn("invite_url", mock_script)
        self.assertIn("delivery_url_base", mock_script)
        self.assertIn("delivery_attempt_count", mock_script)
        self.assertIn("delivery_event_count", mock_script)
        self.assertIn("last_delivery_provider", mock_script)
        self.assertIn("last_delivery_event_type", mock_script)
        self.assertIn("worker_status", mock_script)
        self.assertIn("worker_attempt_count", mock_script)
        self.assertIn("next_worker_run_at", mock_script)
        self.assertIn("Staff invite has been revoked", mock_script)
        self.assertIn("Staff invite has expired", mock_script)
        self.assertIn("refreshStaffUsers", script)
        self.assertIn("refreshSecurityReadiness", script)
        self.assertIn("renderSecurityReadiness", script)
        self.assertIn("renderIdentityReadiness", script)
        self.assertIn("renderIdentityEvidenceRow", script)
        self.assertIn("renderStaffInviteDeliveryReadiness", script)
        self.assertIn("renderStaffInviteDeliveryAdapterReadiness", script)
        self.assertIn("staffInviteDeliveryAdapterReadiness", script)
        self.assertIn("Delivery adapter", script)
        self.assertIn("renderStaffInviteDeliveryOutbox", script)
        self.assertIn("staffInviteDeliveryOutbox", script)
        self.assertIn("Delivery outbox", script)
        self.assertIn("Loading Security Evidence Room", script)
        self.assertIn("Next controls before real user data", script)
        self.assertIn("Evidence room status", script)
        self.assertIn("renderMfaReadiness", script)
        self.assertIn("attestStaffMfa", script)
        self.assertIn("createStaffUser", script)
        self.assertIn("disableStaffUser", script)
        self.assertIn("reactivateStaffUser", script)
        self.assertIn("data-attest-mfa-email", script)
        self.assertIn("data-disable-user-email", script)
        self.assertIn("data-reactivate-user-email", script)
        self.assertIn("refreshStaffInvites", script)
        self.assertIn("refreshStaffSessions", script)
        self.assertIn("revokeStaffSession", script)
        self.assertIn("renderStaffInviteHealth", script)
        self.assertIn("staffInviteDeliveryReadiness", script)
        self.assertIn("Adapter config", script)
        self.assertIn("Missing env", script)
        self.assertIn("createStaffInvite", script)
        self.assertIn("markStaffInviteDelivered", script)
        self.assertIn("retryStaffInviteDelivery", script)
        self.assertIn("webhook event(s)", script)
        self.assertIn("rotateStaffInvite", script)
        self.assertIn("revokeStaffInvite", script)
        self.assertIn("data-retry-delivery-token", script)
        self.assertIn("data-deliver-invite-token", script)
        self.assertIn("data-rotate-invite-token", script)
        self.assertIn("data-revoke-invite-token", script)
        self.assertIn("data-revoke-session-id", script)
        self.assertIn("queue_delivery", script)
        self.assertIn("Queue local delivery receipt", markup)
        self.assertIn("delivery_attempt", script)
        self.assertIn("Token preview", script)
        self.assertIn("one-time URL", script)
        self.assertIn("Staff Invite v3", markup)
        self.assertIn('id="staffInviteDeliveryReadiness"', markup)
        self.assertIn('id="staffInviteDeliveryAdapterReadiness"', markup)
        self.assertIn('id="staffInviteDeliveryOutbox"', markup)
        self.assertIn('id="staffInviteHealth"', markup)
        self.assertIn('id="staffSessions"', markup)
        self.assertIn('id="refreshStaffSessions"', markup)
        self.assertIn("organization_id", script)
        self.assertIn("mfiApplications", mock_script)
        self.assertIn("pavlodar-demo-mfi", mock_script)
        self.assertIn("refreshOrganizations", script)
        self.assertIn("createOrganization", script)
        self.assertIn("syncOrganizationSelect", script)
        self.assertIn("checkApiAndOrganizations", script)
        self.assertIn("refreshModelStatus", script)
        self.assertIn("refreshModelVersions", script)
        self.assertIn("createModelVersion", script)
        self.assertIn("activateModelVersion", script)
        self.assertIn("runPortfolioSimulation", script)
        self.assertIn("runPolicySweep", script)
        self.assertIn("runSensitivitySweep", script)
        self.assertIn("simulationPolicyOptions", script)
        self.assertIn("sensitivityVariants", script)
        self.assertIn("renderPortfolioSimulation", script)
        self.assertIn("renderSimulationCockpit", script)
        self.assertIn("renderSimulationPolicyMemo", script)
        self.assertIn("renderPolicySweep", script)
        self.assertIn("renderSensitivitySweep", script)
        self.assertIn("renderMonteCarloCommitteeBrief", script)
        self.assertIn("committeeBriefSummary", script)
        self.assertIn("committeeBriefSeverityClass", script)
        self.assertIn("copyCommitteeBriefText", script)
        self.assertIn("renderMonteCarloRiskAppetiteGate", script)
        self.assertIn("riskAppetiteGateSummary", script)
        self.assertIn("riskAppetiteAggregateStatus", script)
        self.assertIn("riskAppetiteStatusLabel", script)
        self.assertIn("copyRiskAppetiteGateText", script)
        self.assertIn("renderMonteCarloPilotMonitoringPlan", script)
        self.assertIn("pilotMonitoringPlanSummary", script)
        self.assertIn("pilotMonitoringMetricRows", script)
        self.assertIn("pilotMonitoringCadence", script)
        self.assertIn("pilotMonitoringTriggerRows", script)
        self.assertIn("copyPilotMonitoringPlanText", script)
        self.assertIn("renderMonteCarloPilotEvidenceDossier", script)
        self.assertIn("pilotEvidenceDossierSummary", script)
        self.assertIn("dossierStatusLabel", script)
        self.assertIn("copyPilotEvidenceDossierText", script)
        self.assertIn("policySweepRows", script)
        self.assertIn("sensitivitySweepRows", script)
        self.assertIn("largestSensitivityDriverRow", script)
        self.assertIn("simulationCockpitPosture", script)
        self.assertIn("simulationPolicyMemo", script)
        self.assertIn("simulationScenarioComparisonRows", script)
        self.assertIn("simulationScenarioLookup", script)
        self.assertIn("simulationScenarioDirective", script)
        self.assertIn("formatSignedAmountUnits", script)
        self.assertIn("formatSignedPercent", script)
        self.assertIn("renderSimulationScenario", script)
        self.assertIn("refreshSimulationHistory", script)
        self.assertIn("loadStoredSimulation", script)
        self.assertIn("portfolio_fingerprint", script)
        self.assertIn("portfolio_result_mean_standard_error", script)
        self.assertIn("probability_of_loss", script)
        self.assertIn("borrower_iterations", script)
        self.assertIn("Loss corridor", script)
        self.assertIn("Median stress gap", script)
        self.assertIn("Default drift", script)
        self.assertIn("Policy comparison memo", script)
        self.assertIn("Policy sweep frontier", script)
        self.assertIn("Frontier leader", script)
        self.assertIn("Assumption sensitivity", script)
        self.assertIn("largest stress driver", script)
        self.assertIn("Committee brief", script)
        self.assertIn("Committee-ready planning brief", script)
        self.assertIn("MicroScore Monte Carlo committee brief", script)
        self.assertIn("data-copy-committee-brief", script)
        self.assertIn("Risk appetite gate", script)
        self.assertIn("Pilot allowed only inside explicit guardrails", script)
        self.assertIn("MicroScore Monte Carlo risk appetite gate", script)
        self.assertIn("data-copy-risk-appetite", script)
        self.assertIn("Pilot monitoring plan", script)
        self.assertIn("Controlled pilot monitoring plan", script)
        self.assertIn("MicroScore Monte Carlo pilot monitoring plan", script)
        self.assertIn("data-copy-pilot-monitoring", script)
        self.assertIn("Pilot evidence dossier", script)
        self.assertIn("Committee dossier is ready", script)
        self.assertIn("MicroScore Monte Carlo pilot evidence dossier", script)
        self.assertIn("data-copy-pilot-dossier", script)
        self.assertIn("Capital buffer", script)
        self.assertIn("Loss spread", script)
        self.assertIn("simulation-cockpit", script)
        self.assertIn("simulation-policy-memo", script)
        self.assertIn("simulation-sweep-results", script)
        self.assertIn("simulation-sweep-table", script)
        self.assertIn("simulation-sensitivity-results", script)
        self.assertIn("simulation-sensitivity-table", script)
        self.assertIn("simulation-committee-brief", script)
        self.assertIn("simulation-committee-grid", script)
        self.assertIn("simulation-risk-appetite", script)
        self.assertIn("simulation-risk-appetite-grid", script)
        self.assertIn("simulation-monitoring-plan", script)
        self.assertIn("simulation-monitoring-metrics", script)
        self.assertIn("simulation-evidence-dossier", script)
        self.assertIn("simulation-dossier-artifacts", script)
        self.assertIn("simulation-comparison-table", script)
        self.assertIn("simulation-scenario-directive", script)
        self.assertIn("simulation-warnings", script)
        self.assertIn("stale_model_version", mock_script)
        self.assertIn("model_version_activated", mock_script)
        self.assertIn("activeModelVersion", mock_script)
        self.assertIn(".organization-form", styles)
        self.assertIn(".model-version-form", styles)
        self.assertIn(".model-version-card", styles)
        self.assertIn(".monte-carlo-panel", styles)
        self.assertIn(".simulation-form", styles)
        self.assertIn(".simulation-card", styles)
        self.assertIn(".simulation-cockpit", styles)
        self.assertIn(".simulation-cockpit-grid", styles)
        self.assertIn(".simulation-cockpit-steps", styles)
        self.assertIn(".simulation-policy-memo", styles)
        self.assertIn(".simulation-policy-memo-badges", styles)
        self.assertIn(".simulation-comparison-table", styles)
        self.assertIn(".simulation-policy-actions", styles)
        self.assertIn(".simulation-sweep-results", styles)
        self.assertIn(".simulation-sweep-hero", styles)
        self.assertIn(".simulation-sweep-badges", styles)
        self.assertIn(".simulation-sweep-table", styles)
        self.assertIn(".simulation-sweep-decision", styles)
        self.assertIn(".simulation-sensitivity-results", styles)
        self.assertIn(".simulation-sensitivity-hero", styles)
        self.assertIn(".simulation-sensitivity-badges", styles)
        self.assertIn(".simulation-sensitivity-table", styles)
        self.assertIn(".simulation-sensitivity-decision", styles)
        self.assertIn(".simulation-committee-brief", styles)
        self.assertIn(".simulation-committee-hero", styles)
        self.assertIn(".simulation-committee-grid", styles)
        self.assertIn(".simulation-committee-actions", styles)
        self.assertIn(".simulation-risk-appetite", styles)
        self.assertIn(".simulation-risk-appetite-hero", styles)
        self.assertIn(".simulation-risk-appetite-grid", styles)
        self.assertIn(".simulation-risk-appetite-checks", styles)
        self.assertIn(".simulation-risk-appetite-actions", styles)
        self.assertIn(".gate-block", styles)
        self.assertIn(".check-watch", styles)
        self.assertIn(".simulation-monitoring-plan", styles)
        self.assertIn(".simulation-monitoring-hero", styles)
        self.assertIn(".simulation-monitoring-metrics", styles)
        self.assertIn(".simulation-monitoring-cadence", styles)
        self.assertIn(".simulation-monitoring-triggers", styles)
        self.assertIn(".simulation-monitoring-actions", styles)
        self.assertIn(".monitor-block", styles)
        self.assertIn(".metric-watch", styles)
        self.assertIn(".simulation-evidence-dossier", styles)
        self.assertIn(".simulation-dossier-hero", styles)
        self.assertIn(".simulation-dossier-meta", styles)
        self.assertIn(".simulation-dossier-artifacts", styles)
        self.assertIn(".simulation-dossier-checklist", styles)
        self.assertIn(".simulation-dossier-actions", styles)
        self.assertIn(".dossier-blocked", styles)
        self.assertIn(".artifact-missing", styles)
        self.assertIn(".brief-defensive", styles)
        self.assertIn(".is-largest-driver", styles)
        self.assertIn(".is-frontier-leader", styles)
        self.assertIn(".memo-defensive", styles)
        self.assertIn(".simulation-scenario-directive", styles)
        self.assertIn(".cockpit-defensive", styles)
        self.assertIn(".directive-watch", styles)
        self.assertIn(".simulation-warnings", styles)
        self.assertIn(".simulation-history-row", styles)
        self.assertIn(".risk-readiness", styles)
        self.assertIn(".identity-readiness", styles)
        self.assertIn(".invite-delivery-readiness", styles)
        self.assertIn(".invite-delivery-adapter-readiness", styles)
        self.assertIn(".invite-delivery-outbox", styles)
        self.assertIn(".evidence-hero", styles)
        self.assertIn(".evidence-summary-grid", styles)
        self.assertIn(".evidence-row", styles)
        self.assertIn(".severity-blocker", styles)
        self.assertIn(".review-action-plan", styles)
        self.assertIn(".action-plan-grid", styles)
        self.assertIn(".action-plan-blockers", styles)
        self.assertIn(".affordability-panel", styles)
        self.assertIn(".decision-history", styles)
        self.assertIn(".validation-summary", styles)
        self.assertIn(".field-invalid", styles)
        self.assertIn(".field-error", styles)
        self.assertIn(".settlement-bars", styles)
        self.assertIn(".settlement-risk-row", styles)
        self.assertIn(".portfolio-snapshot-note", styles)
        self.assertIn(".settlement-fill-industrial_city", styles)
        self.assertIn("simulatePortfolio", mock_script)
        self.assertIn("portfolioFingerprint", mock_script)
        self.assertIn("simulationStandardError", mock_script)
        self.assertIn("simulationSummary", mock_script)
        self.assertIn("seededRandom", mock_script)
        self.assertIn("scenarioShifts", mock_script)
        self.assertIn("portfolio_simulation_run", mock_script)
        self.assertIn("enterDemoWorkspace", script)
        self.assertIn("API settings", markup)
        self.assertIn("roleAllowedViews", script)
        self.assertIn("configureRoleNavigation", script)
        self.assertIn("setAppMode", script)
        self.assertIn("routeToView", script)
        self.assertIn("viewToRoute", script)
        self.assertIn("roleDefaultRoutes", script)
        self.assertIn("applyRoute", script)
        self.assertIn("mfiSectionJumps", script)
        self.assertIn("scrollToMfiSection", script)
        self.assertIn('document.getElementById(targetId)', script)
        self.assertIn('scrollIntoView({ behavior: "smooth", block: "start" })', script)
        self.assertIn('target.focus({ preventScroll: true })', script)
        self.assertIn('els.applicationsTable.className = "mfi-queue-list"', script)
        self.assertIn("renderSelectedApplicationBrief", script)
        self.assertIn("analystBriefAction", script)
        self.assertIn("mfiInspectorTab", script)
        self.assertIn("syncMfiInspectorTabs", script)
        self.assertIn("setMfiInspectorTab", script)
        self.assertIn("renderMfiInspectorSummary", script)
        self.assertIn("renderDecisionInspector", script)
        self.assertIn("renderTimelineInspector", script)
        self.assertIn("renderDecisionHistoryRows", script)
        self.assertIn("mfiInspectorTabs.forEach", script)
        self.assertIn("ArrowRight", script)
        self.assertIn("MFI_QUEUE_FILTER_DEFAULTS", script)
        self.assertIn("filteredMfiQueueApplications", script)
        self.assertIn("sortMfiQueueApplications", script)
        self.assertIn("applyMfiQueueFilters", script)
        self.assertIn("renderMfiQueueSummary", script)
        self.assertIn("mfiQueueSearch.addEventListener", script)
        self.assertIn("clearMfiQueueFilters.addEventListener", script)
        self.assertIn('data-mfi-brief-jump="mfiDetailPanel"', script)
        self.assertIn("Request / income", script)
        self.assertIn("Next analyst move", script)
        self.assertIn('class="mfi-queue-card', script)
        self.assertIn('data-application-id="${escapeHtml(application.id)}"', script)
        self.assertIn("formatPolicyName(riskBand)", script)
        self.assertIn("mfi-queue-card-meta", script)
        self.assertNotIn("<th>Status</th><th>Borrower</th><th>Amount</th><th>District</th><th>Risk</th><th>Decision</th>", script)
        self.assertIn("replaceRoute", script)
        self.assertIn("hashchange", script)
        self.assertIn("#/login", script)
        self.assertIn("#/borrower", script)
        self.assertIn("#/mfi", script)
        self.assertIn("#/admin", script)
        self.assertIn('data-roles="borrower"', markup)
        self.assertIn('data-roles="mfi_analyst admin"', markup)
        self.assertIn('data-roles="admin"', markup)

    def test_one_click_launcher_is_documented(self) -> None:
        root_readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        web_readme = (WEB_ROOT / "README.md").read_text(encoding="utf-8")
        command_file = (PROJECT_ROOT / "Start-MicroScore.cmd").read_text(encoding="utf-8")

        self.assertIn("Start-MicroScore.cmd", root_readme)
        self.assertIn("Start-MicroScore.cmd", web_readme)
        self.assertIn("microscore_api.dev", command_file)

    def test_static_demo_deployment_is_configured(self) -> None:
        workflow = PAGES_WORKFLOW.read_text(encoding="utf-8")
        deployment_doc = (PROJECT_ROOT / "docs" / "STATIC_DEMO_DEPLOYMENT.md").read_text(
            encoding="utf-8",
        )

        self.assertIn("actions/configure-pages@v6", workflow)
        self.assertIn("actions/upload-pages-artifact@v5", workflow)
        self.assertIn("actions/deploy-pages@v5", workflow)
        self.assertIn("pages: write", workflow)
        self.assertIn("id-token: write", workflow)
        self.assertIn("path: apps/web", workflow)
        self.assertIn("GitHub Pages", deployment_doc)
        self.assertIn("application-intake.js", deployment_doc)
        self.assertIn("portfolio-dashboard.js", deployment_doc)
        self.assertIn("mock-api.js", deployment_doc)
        self.assertIn("synthetic", deployment_doc)


if __name__ == "__main__":
    unittest.main()
