from __future__ import annotations

import sys
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

WEB_ROOT = PROJECT_ROOT / "apps" / "web"
PAGES_WORKFLOW = PROJECT_ROOT / ".github" / "workflows" / "pages.yml"


class WebStaticTests(unittest.TestCase):
    def test_frontend_files_are_present(self) -> None:
        self.assertTrue((PROJECT_ROOT / "Start-MicroScore.cmd").exists())
        self.assertTrue((WEB_ROOT / "index.html").exists())
        self.assertTrue((WEB_ROOT / "styles.css").exists())
        self.assertTrue((WEB_ROOT / "app.js").exists())
        self.assertTrue((WEB_ROOT / "mock-api.js").exists())
        self.assertTrue((WEB_ROOT / ".nojekyll").exists())
        self.assertTrue((WEB_ROOT / "README.md").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "favicon-32.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "apple-touch-icon.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "microscore-mark.svg").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score.png").exists())
        self.assertTrue((WEB_ROOT / "assets" / "micro-score-lockup.png").exists())

    def test_html_loads_styles_and_script(self) -> None:
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        css = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn('href="./styles.css"', html)
        self.assertIn('href="./assets/favicon.svg"', html)
        self.assertIn('href="./assets/favicon-32.png"', html)
        self.assertIn('href="./assets/apple-touch-icon.png"', html)
        self.assertIn('href="./assets/micro-score.png"', html)
        self.assertIn('src="./assets/micro-score-lockup.png?v=20260612-full"', html)
        self.assertIn('src="./assets/microscore-mark.svg"', html)
        self.assertIn('src="./mock-api.js?v=20260613-static-demo"', html)
        self.assertIn('src="./app.js?v=20260613-static-demo"', html)
        self.assertIn("window.history.replaceState", html)
        self.assertIn("synthetic demo data only", html)
        self.assertIn('name="requested_amount" type="number" min="1000" step="1"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1" step="1000"', html)
        self.assertNotIn('name="requested_amount" type="number" min="1000" step="1000"', html)
        self.assertIn('name="annual_income" type="number" min="0" step="1"', html)
        self.assertIn('name="total_outstanding_debt" type="number" min="0" step="1"', html)
        self.assertIn('name="avg_deposit_amount" type="number" min="0" step="1"', html)
        self.assertIn('name="debit_card_spending" type="number" min="0" step="1"', html)
        self.assertIn('id="authScreen"', html)
        self.assertIn('id="appShell"', html)
        self.assertIn('id="connection-title"', html)
        self.assertIn('class="api-settings"', html)
        self.assertIn('aria-label="Check API"', html)
        self.assertIn('id="demoModePill"', html)
        self.assertIn('id="resetDemoData"', html)
        self.assertIn('class="reviewer-snapshot"', html)
        self.assertIn("Research + product prototype", html)
        self.assertIn("Synthetic Pavlodar demo", html)
        self.assertIn("Human review support", html)
        self.assertIn("password123", html)
        self.assertNotIn('id="role"', html)
        self.assertIn(
            "grid-template-columns: minmax(190px, 1.15fr) minmax(180px, 0.85fr) auto auto",
            css,
        )
        self.assertIn('id="borrowerConsent"', html)
        self.assertIn("synthetic-data demo", html)
        self.assertIn("real borrower", html)
        self.assertIn('hidden', html)
        self.assertIn('id="borrowerView"', html)
        self.assertIn('id="mfiView"', html)
        self.assertIn('id="adminView"', html)
        self.assertIn('id="staffForm"', html)
        self.assertIn('id="staffUsers"', html)
        self.assertIn('id="refreshUsers"', html)
        self.assertIn('id="organizationForm"', html)
        self.assertIn('id="organizationDirectory"', html)
        self.assertIn('id="refreshOrganizations"', html)
        self.assertIn('id="applicationOrganization"', html)
        self.assertIn('id="staffOrganization"', html)
        self.assertIn('id="modelStatusPill"', html)
        self.assertIn('id="modelVersionForm"', html)
        self.assertIn('id="modelVersionRegistry"', html)
        self.assertIn('id="refreshModelVersions"', html)
        self.assertIn("Version registry", html)
        self.assertIn('id="simulationForm"', html)
        self.assertIn('id="runSimulation"', html)
        self.assertIn('id="simulationResults"', html)
        self.assertIn('id="simulationHistory"', html)
        self.assertIn('id="refreshSimulationHistory"', html)
        self.assertIn("Monte Carlo Lab", html)
        self.assertIn("This does not change borrower scores", html)
        self.assertIn('name="organization_id"', html)
        self.assertIn("Pavlodar Demo MFI", html)

    def test_hidden_screens_are_not_scrollable_before_login(self) -> None:
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")

        self.assertIn("[hidden]", styles)
        self.assertIn("display: none !important;", styles)
        self.assertIn(".reviewer-snapshot", styles)
        self.assertIn(".consent-panel", styles)
        self.assertIn("accent-color: var(--teal);", styles)

    def test_frontend_targets_current_api_contract(self) -> None:
        markup = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        script = (WEB_ROOT / "app.js").read_text(encoding="utf-8")
        mock_script = (WEB_ROOT / "mock-api.js").read_text(encoding="utf-8")

        expected_paths = [
            "/health",
            "/auth/register",
            "/auth/login",
            "/applications",
            "/timeline",
            "/mfi/applications",
            "/mfi/model-status",
            "/mfi/applications/export.csv",
            "/decision",
            "/review-packet",
            "/mfi/analytics/segments",
            "/mfi/analytics/policies",
            "/mfi/simulations/portfolio",
            "/mfi/simulations",
            "/mfi/analytics/decisions",
            "/admin/audit-events",
            "/admin/model-versions",
            "/admin/applications",
        ]
        for path in expected_paths:
            self.assertIn(path, script)
        self.assertIn("Scenario comparison", script)
        self.assertIn("Recommendation", script)
        self.assertIn("Local explanation", script)
        self.assertIn("MFI decision", script)
        self.assertIn("saveApplicationDecision", script)
        self.assertIn("Review packet", markup)
        self.assertIn("loadReviewPacket", script)
        self.assertIn("renderReviewPacket", script)
        self.assertIn("Application timeline", script)
        self.assertIn("renderApplicationTimeline", script)
        self.assertIn("Export CSV", markup)
        self.assertIn("exportApplicationsCsv", script)
        self.assertIn("microscore-applications.csv", script)
        self.assertIn("Analyst decisions", script)
        self.assertIn("renderPortfolioDecisionSnapshot", script)
        self.assertIn("Decision audit", markup)
        self.assertIn("decisionAuditRows", script)
        self.assertIn("proxy_sensitivity_delta", script)
        self.assertIn("HIGH_PROXY_SENSITIVITY_DELTA", script)
        self.assertIn("renderModelUseNotice", script)
        self.assertIn("Decision-support only", script)
        self.assertIn("Manual review required", script)
        self.assertIn("not validated for real lending decisions", script)
        self.assertIn("decision_support", script)
        self.assertIn("top_positive_factors", script)
        self.assertIn("top_protective_factors", script)
        self.assertIn("Portfolio", markup)
        self.assertIn("renderDistrictRiskRows", script)
        self.assertIn("renderPortfolioOverview", script)
        self.assertIn("Policy Lab", markup)
        self.assertIn("renderPolicyAnalytics", script)
        self.assertIn("resetApplicationViews", script)
        self.assertIn("renderStateBlock", script)
        self.assertIn("setPanelState", script)
        self.assertIn("withButtonBusy", script)
        self.assertIn("Loading application queue", script)
        self.assertIn("Queue unavailable", script)
        self.assertIn("Scoring application", script)
        self.assertIn("Review packet unavailable", script)
        self.assertIn("Refreshing policy lab", script)
        self.assertIn("Decision audit unavailable", script)
        self.assertIn('removeItem("microscore.lastApplicationId")', script)
        self.assertIn("API_BASE_CANDIDATES", script)
        self.assertIn("MicroScoreMockApi", script)
        self.assertIn("MicroScoreMockApi", mock_script)
        self.assertIn("Static demo mode", script)
        self.assertIn("forceStaticDemo", script)
        self.assertIn("hostedStaticPage", script)
        self.assertIn("LOCAL_HOSTNAMES", script)
        self.assertIn("syncConnectionPanel", script)
        self.assertIn("Demo system", script)
        self.assertIn("Local system", script)
        self.assertIn("apiSettings.hidden = demoMode", script)
        self.assertIn("localhost plumbing", script)
        self.assertIn("resetStaticDemoData", script)
        self.assertIn("resetDemo", script)
        self.assertIn("borrowerConsent", script)
        self.assertIn("borrowerConsentAcknowledged", script)
        self.assertIn("Confirm demo data consent", script)
        self.assertIn("DEMO_CONSENT_VERSION", script)
        self.assertIn("consent_confirmed", script)
        self.assertIn("consent_version", script)
        self.assertIn("logoutSession", script)
        self.assertIn('/auth/logout', script)
        self.assertIn('payload.role = "borrower"', script)
        self.assertIn("formatApiError", script)
        styles = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".model-use-notice", styles)
        self.assertIn(".notice-caution", styles)
        self.assertIn(".state-block", styles)
        self.assertIn(".state-spinner", styles)
        self.assertIn("@keyframes stateSpin", styles)
        self.assertIn("button:disabled", styles)
        self.assertIn("/mfi/applications/export.csv", mock_script)
        self.assertIn("/mfi/analytics/policies", mock_script)
        self.assertIn("/admin/applications", mock_script)
        self.assertIn("validateApplicationPrivacy", mock_script)
        self.assertIn("findForbiddenSignalPaths", mock_script)
        self.assertIn("Remove sensitive personal fields", mock_script)
        self.assertIn('/auth/logout', mock_script)
        self.assertIn("Demo session expired", mock_script)
        self.assertIn("passwordPolicyViolations", mock_script)
        self.assertIn("Public registration is limited to borrower accounts", mock_script)
        self.assertIn('"/admin/users"', mock_script)
        self.assertIn("staff_user_created", mock_script)
        self.assertIn("refreshStaffUsers", script)
        self.assertIn("createStaffUser", script)
        self.assertIn("organization_id", script)
        self.assertIn("mfiApplications", mock_script)
        self.assertIn("pavlodar-demo-mfi", mock_script)
        self.assertIn("refreshOrganizations", script)
        self.assertIn("createOrganization", script)
        self.assertIn("syncOrganizationSelect", script)
        self.assertIn("checkApiAndOrganizations", script)
        self.assertIn("refreshModelStatus", script)
        self.assertIn("refreshModelVersions", script)
        self.assertIn("createModelVersion", script)
        self.assertIn("activateModelVersion", script)
        self.assertIn("runPortfolioSimulation", script)
        self.assertIn("renderPortfolioSimulation", script)
        self.assertIn("renderSimulationScenario", script)
        self.assertIn("refreshSimulationHistory", script)
        self.assertIn("loadStoredSimulation", script)
        self.assertIn("portfolio_fingerprint", script)
        self.assertIn("portfolio_result_mean_standard_error", script)
        self.assertIn("probability_of_loss", script)
        self.assertIn("simulation-warnings", script)
        self.assertIn("stale_model_version", mock_script)
        self.assertIn("model_version_activated", mock_script)
        self.assertIn("activeModelVersion", mock_script)
        self.assertIn(".organization-form", styles)
        self.assertIn(".model-version-form", styles)
        self.assertIn(".model-version-card", styles)
        self.assertIn(".monte-carlo-panel", styles)
        self.assertIn(".simulation-form", styles)
        self.assertIn(".simulation-card", styles)
        self.assertIn(".simulation-warnings", styles)
        self.assertIn(".simulation-history-row", styles)
        self.assertIn("simulatePortfolio", mock_script)
        self.assertIn("portfolioFingerprint", mock_script)
        self.assertIn("simulationStandardError", mock_script)
        self.assertIn("simulationSummary", mock_script)
        self.assertIn("seededRandom", mock_script)
        self.assertIn("scenarioShifts", mock_script)
        self.assertIn("portfolio_simulation_run", mock_script)
        self.assertIn("enterDemoWorkspace", script)
        self.assertIn("API settings", markup)
        self.assertIn("roleAllowedViews", script)
        self.assertIn("configureRoleNavigation", script)
        self.assertIn("setAppMode", script)
        self.assertIn("routeToView", script)
        self.assertIn("viewToRoute", script)
        self.assertIn("roleDefaultRoutes", script)
        self.assertIn("applyRoute", script)
        self.assertIn("replaceRoute", script)
        self.assertIn("hashchange", script)
        self.assertIn("#/login", script)
        self.assertIn("#/borrower", script)
        self.assertIn("#/mfi", script)
        self.assertIn("#/admin", script)
        self.assertIn('data-roles="borrower"', markup)
        self.assertIn('data-roles="mfi_analyst admin"', markup)
        self.assertIn('data-roles="admin"', markup)

    def test_one_click_launcher_is_documented(self) -> None:
        root_readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        web_readme = (WEB_ROOT / "README.md").read_text(encoding="utf-8")
        command_file = (PROJECT_ROOT / "Start-MicroScore.cmd").read_text(encoding="utf-8")

        self.assertIn("Start-MicroScore.cmd", root_readme)
        self.assertIn("Start-MicroScore.cmd", web_readme)
        self.assertIn("microscore_api.dev", command_file)

    def test_static_demo_deployment_is_configured(self) -> None:
        workflow = PAGES_WORKFLOW.read_text(encoding="utf-8")
        deployment_doc = (PROJECT_ROOT / "docs" / "STATIC_DEMO_DEPLOYMENT.md").read_text(
            encoding="utf-8",
        )

        self.assertIn("actions/configure-pages@v5", workflow)
        self.assertIn("actions/upload-pages-artifact@v4", workflow)
        self.assertIn("actions/deploy-pages@v4", workflow)
        self.assertIn("pages: write", workflow)
        self.assertIn("id-token: write", workflow)
        self.assertIn("path: apps/web", workflow)
        self.assertIn("GitHub Pages", deployment_doc)
        self.assertIn("mock-api.js", deployment_doc)
        self.assertIn("synthetic", deployment_doc)


if __name__ == "__main__":
    unittest.main()
