-- MicroScore PostgreSQL Migration Draft v1
-- Version: 0001_initial_schema
-- Purpose: mirror the current SQLite prototype schema with PostgreSQL-native
--          data types before a real PostgreSQL repository backend exists.
-- Safety: this file is a reviewed readiness artifact. It is not executed by the
--         runtime yet and does not make storage production-ready by itself.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mfi_organizations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    region TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    organization_id TEXT REFERENCES mfi_organizations(id),
    created_at TIMESTAMPTZ NOT NULL,
    disabled_at TIMESTAMPTZ,
    disabled_by TEXT REFERENCES users(email),
    mfa_attested_at TIMESTAMPTZ,
    mfa_attested_by TEXT REFERENCES users(email),
    mfa_method TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS staff_invites (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT NOT NULL,
    organization_id TEXT NOT NULL REFERENCES mfi_organizations(id),
    created_by TEXT REFERENCES users(email),
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ,
    accepted_by TEXT REFERENCES users(email),
    revoked_at TIMESTAMPTZ,
    revoked_by TEXT REFERENCES users(email),
    delivered_at TIMESTAMPTZ,
    delivered_by TEXT REFERENCES users(email),
    delivery_channel TEXT,
    delivery_recipient TEXT,
    delivery_url_base TEXT,
    delivery_note TEXT
);

CREATE TABLE IF NOT EXISTS staff_invite_delivery_attempts (
    attempt_id TEXT PRIMARY KEY,
    invite_token TEXT NOT NULL REFERENCES staff_invites(token) ON DELETE CASCADE,
    attempted_at TIMESTAMPTZ NOT NULL,
    attempted_by TEXT REFERENCES users(email),
    provider TEXT NOT NULL,
    status TEXT NOT NULL,
    channel TEXT NOT NULL,
    recipient TEXT,
    delivery_url_base TEXT,
    note TEXT,
    error TEXT,
    worker_status TEXT NOT NULL DEFAULT 'completed',
    worker_attempt_count INTEGER NOT NULL DEFAULT 0,
    next_worker_run_at TIMESTAMPTZ,
    dead_letter_at TIMESTAMPTZ,
    last_worker_error TEXT
);

CREATE TABLE IF NOT EXISTS staff_invite_delivery_events (
    event_id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_event_id TEXT NOT NULL,
    attempt_id TEXT NOT NULL REFERENCES staff_invite_delivery_attempts(attempt_id)
        ON DELETE CASCADE,
    invite_token TEXT NOT NULL REFERENCES staff_invites(token) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    mapped_attempt_status TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ,
    recipient TEXT,
    error TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(provider, provider_event_id)
);

CREATE TABLE IF NOT EXISTS loan_applications (
    id TEXT PRIMARY KEY,
    borrower_email TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    status TEXT NOT NULL,
    requested_amount NUMERIC(14, 2) NOT NULL,
    purpose TEXT NOT NULL,
    district TEXT,
    settlement_type TEXT,
    organization_id TEXT REFERENCES mfi_organizations(id),
    behavioral_signals_json JSONB NOT NULL,
    score_result_json JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    scored_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS application_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id TEXT NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,
    actor_email TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    decision TEXT NOT NULL,
    policy_name TEXT,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    details_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS model_versions (
    version TEXT PRIMARY KEY,
    model_name TEXT NOT NULL,
    model_type TEXT NOT NULL,
    lifecycle_status TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    feature_schema_version TEXT NOT NULL,
    training_data_label TEXT NOT NULL,
    random_state INTEGER NOT NULL,
    metrics_json JSONB NOT NULL,
    limitations_json JSONB NOT NULL,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS portfolio_simulations (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES mfi_organizations(id),
    actor_email TEXT NOT NULL REFERENCES users(email),
    portfolio_fingerprint TEXT NOT NULL,
    request_json JSONB NOT NULL,
    result_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_organization
    ON users(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sessions_email
    ON sessions(email, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_applications_borrower
    ON loan_applications(borrower_email);

CREATE INDEX IF NOT EXISTS idx_applications_organization
    ON loan_applications(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_application_decisions_application
    ON application_decisions(application_id);

CREATE INDEX IF NOT EXISTS idx_audit_entity
    ON audit_events(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_staff_invites_email
    ON staff_invites(email, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_invites_organization
    ON staff_invites(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_invite_delivery_attempts_invite
    ON staff_invite_delivery_attempts(invite_token, attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_invite_delivery_events_attempt
    ON staff_invite_delivery_events(attempt_id, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_invite_delivery_events_invite
    ON staff_invite_delivery_events(invite_token, received_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_model_versions_single_active
    ON model_versions(is_active)
    WHERE is_active IS TRUE;

CREATE INDEX IF NOT EXISTS idx_portfolio_simulations_organization
    ON portfolio_simulations(organization_id, created_at DESC);

INSERT INTO schema_migrations (version, description)
VALUES ('0001_initial_schema', 'Initial PostgreSQL schema draft aligned to SQLite prototype')
ON CONFLICT (version) DO UPDATE
SET description = EXCLUDED.description;

COMMIT;
